vendor/assets/javascripts/ui.js

- ダイアログを表示して自由な名前で保存できる
- 直接保存する場合はa.txtとなる

#10 ファイルをa.txtで保存できるようにした

---

app/views/admins/index.html.erb
app/views/layouts/application.html.erb
app/views/questions/_form.html.erb

- 問題追加のルールのリンクを設定した
- githubへのリンクを追加した
- すべてtarget: "_blank"にしてあるので別タブで表示されるようにした

リンクの追加を行った

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/views/admins/answer.html.erb
app/views/layouts/application.html.erb
app/views/results/code.html.erb
app/views/welcomes/index.html.erb

- coderay+redcarpetを使い管理者ページのコードの表示方法を変更した
- welcomes/indexにtwitterTLを表示するようにした

コードの表示方法を変更したこととTwitterのTLを埋め込んだ

---

Gemfile
app/controllers/sessions_controller.rb
app/models/user.rb

- ユーザがログインした際`update_attributes!`を用いてauthの情報をもとに、ユーザの情報を更新するようにした

#16 ユーザがログインした際情報を更新するようにした

---

app/controllers/admins_controller.rb
app/views/admins/index.html.erb
app/views/admins/list.html.erb
config/routes.rb

- 管理者ページから確認できるようにした
- admins/listに実装した
- adminsコントローラのリファクタリングも行った

問題に対して提出されたコード一覧を見れるようにした

---

app/controllers/admins_controller.rb
app/views/admins/index.html.erb
app/views/categories/show.html.erb
app/views/questions/show.html.erb
app/views/results/index.html.erb
app/views/sections/show.html.erb

-  最新の解答状況を見れるようにした
- 管理画面から解答ページに飛べるようにした

管理者ページを更新した

---

README.md

i translate readme to english.

readme translate

---

app/controllers/lessons_controller.rb
app/controllers/sections_controller.rb
app/controllers/tops_controller.rb
app/views/lessons/index.html.erb
app/views/sections/index.html.erb
app/views/tops/index.html.erb
config/routes.rb

- kaminariを用いたページネーションを利用するため
- １つのコントローラに偏っている責務を分散するため

タブメニューを同期処理に変更した

---

app/controllers/lessons_controller.rb
app/controllers/sections_controller.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/lessons/index.html.erb
app/views/sections/index.html.erb
config/initializers/kaminari_config.rb

- sections/index, lessons/indexにページネーション機能を追加した
- 現在リスト上部に機能を追加したが、今後変更する可能性もある

ページネーション機能を追加した

---

db/migrate/20180619160715_remove_column_to_question.rb
db/schema.rb

Questionテーブルの不要なカラムを削除した

---

Dockerfile
README.md
app/controllers/api/v1/compile_controller.rb
app/controllers/api/v1/judgement_controller.rb
app/views/codes/index.html.erb
app/views/lessons/show.html.erb
app/views/tops/index.html.erb
lib/code_candy/compiler.rb
lib/code_candy/container.rb
vendor/assets/javascripts/ui.js

- lib/code_candyをアップデートした
- Swiftを実行できるようにした
- コンテナをopenjdk:10からswiftに変更した
- コンテナの変更に伴い、Debian8からUbuntu16.04に変更した
- Ace Editorのバージョンを変更した
- Javaのバージョンを10から8に変更した
- コンテナを変更したため
- 後々10に戻す

実行モジュールをアップデートした

---

app/views/admins/index.html.erb

.strftime("%Y年 %m月 %d日 %H:%M:%S")
で日本語っぽいフォーマットにしてみたけど
Rubyやったことないから動くかどうかわからないので慎重にお願いします

解答時刻フォーマットを編集 #81

---

README.md
lib/code_candy/compiler.rb
lib/code_candy/language.rb

- case-when文で実装していた各言語の実行データをlanguage.rbを作成し可読性を向上させた

実行モジュールを改良した

---

app/controllers/api/v1/judgement_controller.rb
app/controllers/questions_controller.rb

- production環境でのみ問題作成時にツイートするようにした。
- 問題解答APIをログイン認証されているユーザのみが利用できるようにした。

APIの利用制限を設定した

---

app/controllers/api/api_controller.rb
app/controllers/api/v1/compile_controller.rb
app/controllers/api/v1/judgement_controller.rb

- app/controller/apiの改良を行った
- 機能の追加は行っていない

APIの改良を行った

---

app/controllers/api/v1/information_controller.rb
config/routes.rb

- `/api/v1/information/result`で取得できる

投稿されているプログラムの言語の割合を返却するAPIを実装した

---

app/controllers/api/v1/heatmap_controller.rb
app/views/tops/index.html.erb
config/initializers/assets.rb
config/routes.rb
vendor/assets/javascripts/heatmap.js
vendor/assets/stylesheets/heatmap.css

ヒートマップを追加した

---

lib/code_candy/compiler.rb
lib/code_candy/parameter.rb
public/404.html
public/422.html
public/500.html

エラーページを編集した

---

app/controllers/welcomes_controller.rb

-  ResultテーブルまたはCodeテーブルにデータが存在しない場合にエラーがでていた問題を修正した。

welcomesコントローラの設定を変更した

---

app/controllers/welcomes_controller.rb

welcomesコントローラのバグを修正した

---

app/views/admins/_code.html.erb
app/views/admins/_situation.html.erb
app/views/admins/_user.html.erb
app/views/layouts/application.html.erb
config/initializers/assets.rb

- google_oauth2認証の時screen_nameが存在しないので、user_nameを表示するようにした
- google_oauth2認証の時screen_nameもuser_nameも表示しないと行けない場合、どちらもuser_nameを表示するようにした

Adminページの表示内容を変更した

---

app/controllers/application_controller.rb
app/views/codes/index.html.erb
app/views/lessons/show.html.erb
docker/compiler_default/Dockerfile
lib/code_candy/language.rb
lib/code_candy/parameter.rb
vendor/assets/javascripts/ui.js

Haskellの実行環境を整えた

---

app/assets/javascripts/code_golf_rankings.coffee
app/assets/stylesheets/code_golf_rankings.scss
app/controllers/code_golf_rankings_controller.rb
app/controllers/lessons_controller.rb
app/helpers/code_golf_rankings_helper.rb
app/views/code_golf_rankings/index.html.erb
app/views/code_golf_rankings/show.html.erb
app/views/lessons/index.html.erb
app/views/lessons/show.html.erb
app/views/sections/index.html.erb
app/views/tops/index.html.erb
config/routes.rb
spec/controllers/code_golf_rankings_controller_spec.rb
spec/helpers/code_golf_rankings_helper_spec.rb
spec/views/code_golf_rankings/index.html.erb_spec.rb
spec/views/code_golf_rankings/show.html.erb_spec.rb

Code Golf Rankingの機能を実装した

---

Gemfile
Gemfile.lock
config/initializers/rack_mini_profiler.rb
lib/code_candy/compiler.rb
lib/code_candy/container.rb

ライブラリのリファクタリングを行った

---

.circleci/config.yml
config/database.circleci.yml
lib/code_candy/compiler_logic.rb
spec/controllers/code_golf_rankings_controller_spec.rb
spec/controllers/editors_controller_spec.rb
spec/helpers/code_golf_rankings_helper_spec.rb
spec/helpers/editors_helper_spec.rb
spec/models/code_spec.rb
spec/views/code_golf_rankings/index.html.erb_spec.rb
spec/views/code_golf_rankings/show.html.erb_spec.rb
spec/views/editors/index.html.erb_spec.rb

- テストの自動化が行えていないのでその設定は別に行う
- 理由: Dockerコンテナを用いたテストがCI上ではうまく動作しなかったため(ローカル環境ではテストは通っている)

CircleCIの設定を構築した #148

---

Gemfile
Gemfile.lock
app/controllers/admins_controller.rb
app/views/admins/_user.html.erb
config/environments/development.rb

- 管理者ページの表示が遅い問題があった
- 原因調査にbulletを導入し、bulletよりN+1クエリが発生していることがわかった
- N+1クエリを実行しないようにコントローラの処理を変更した

管理者ページの高速化を行った #169

---

app/views/tops/index.html.erb
vendor/assets/javascripts/heatmap.js

- 1年分のみHeatmapを表示するように機能を変更した
- 後に過去のHeatmapも参照できる機能を実装する

heatmapの表示を変更した

---

lib/code_candy/compiler.rb

- workdirがコンフリクトを行わないようにユーザ毎に作成するようにした
- 実行言語がサーバに対応しているかチェックする処理を改良した

compiler.rbの処理を変更した

---

app/views/clouds/compiler.html.erb
app/views/codes/index.html.erb
spec/models/cloud_compiler_spec.rb

タブメニューの共通化は行っていないが、全ページにタブメニューの設置を行った。
共通化を行っていない理由として、アクティブなタブがページによって違うからである。

タブメニューを追加した #245

---

lib/code_candy/code_runner.rb
lib/code_candy/judgement.rb
spec/lib/code_candy/code_runner_spec.rb

execメソッドの引数をinitializeメソッドの引数に変更し、インスタンス単位で実行環境を構築するようにした。

code_runnerの改良を行った
